db_uri: mongodb://mongodb:27017/open5gs
logger:
  level: info
smf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777
        advertise: smf
    client:
      nrf:
        - uri: http://nrf:7777
    no_tls: true
  pfcp:
    server:
      - address: {{ smf_n4_ip }}  # SMF su n4
        port: 8805
    client:
      upf:
        - address: {{ upf_cloud_n4_ip }}  # N4 upf-cloud
          dnn: [internet, mec]
  gtpc:
    server:
      - address: {{ smf_n4_ip }}
  gtpu:
    server:
      - address: {{ smf_n4_ip }}
  session:
    - subnet: {{ ue_internet_subnet }}
      gateway: {{ ue_internet_gateway }}
      dnn: internet
    - subnet: {{ ue_mec_subnet }}
      gateway: {{ ue_mec_gateway }}
      dnn: mec
  dns:
{% for server in ue_dns_servers %}
    - {{ server }}
{% endfor %}
  mtu: {{ ue_mtu }}
  metrics:
    server:
      - address: 0.0.0.0
        port: 9090
