logger:
  level: info
upf:
  pfcp:
    server:
      - address: {{ upf_cloud_n4_ip }}
        port: 8805
  gtpu:
    server:
      - address: {{ upf_cloud_n3_ip }}
  session:
    - subnet: {{ ue_internet_subnet }}
      gateway: {{ ue_internet_gateway }}
      dnn: internet
      dev: ogstun
    - subnet: {{ ue_mec_subnet }}
      gateway: {{ ue_mec_gateway }}
      dnn: mec
      dev: ogstun2
  metrics:
    server:
      - address: 0.0.0.0
        port: 9090
