from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="DASHBOARD_", env_file=".env", extra="ignore")

    app_name: str = "5G Dashboard API"
    app_env: str = "dev"
    mode: str = "prod"
    runtime_source: str = "unknown"
    host: str = "0.0.0.0"
    port: int = 8080

    kubeconfig_path: str = "/vagrant/tests/kubeconfig"

    worker_ssh_host: str = "worker"
    shell_timeout_seconds: int = 10

    # n6m (5G MEC data network) attachment for PUSH positioning adapters. An edge
    # scanner POSTs observations over 5G, so a push adapter must be reachable on
    # n6m; the deploy path auto-attaches each listed adapter at its reserved IP.
    # Values plumbed from all.yml (n6m_push_adapters, nad_n6m_*) by phase 09.
    # n6m_push_adapters is a compact "name=cidr,name=cidr" string.
    # Pool NAD for attachments without a fixed address, static NAD for the rest
    # (reserved-band app IPs, push adapters). Set by phase 09 from all.yml.
    n6m_nad_name: str
    n6m_static_nad_name: str
    n6m_nad_namespace: str
    n6m_push_adapters: str = ""

    def n6m_push_adapter_map(self) -> dict[str, str]:
        """Parse n6m_push_adapters into {adapter_name: cidr}. Malformed entries
        are skipped, so a typo in config never breaks a deploy."""
        out: dict[str, str] = {}
        for pair in self.n6m_push_adapters.split(","):
            pair = pair.strip()
            if "=" in pair:
                name, cidr = pair.split("=", 1)
                name, cidr = name.strip(), cidr.strip()
                if name and cidr:
                    out[name] = cidr
        return out
    shell_max_output_bytes: int = 1_000_000

    # Set by phase 09 (dashboard-backend.service) from the worker's inventory address.
    prometheus_url: str
    mongodb_url: str

    # Set by phase 09 (DASHBOARD_ADMIN_TOKEN, generated by the kelt CLI); guards the watchdog.
    admin_token: str = ""
    allow_configmap_write: bool = False
    # Gate for the Northbound console's deploy-from-image endpoint, which creates
    # arbitrary Deployments/Services/Secrets in the northbound namespaces. Off by
    # default (read-only console); phase 09 sets DASHBOARD_ALLOW_WORKLOAD_CREATE=true
    # to enable it. Always admin-gated on top of this. See docs/security/iam.md.
    allow_workload_create: bool = False
    # Edge apps platform (phase 12). The namespace the Apps console deploys into
    # is all.yml apps_namespace (read through network_plan.plan_value).
    # Registry host as it appears in image tags (<host>/<name>:<tag>); shown in the
    # Apps page so the operator knows where to docker push. Empty if the platform
    # is not configured. Mirrors all.yml apps_registry_host.
    apps_registry_host: str = ""
    # Registry basic-auth, surfaced to admins in the Apps page (show/hide) so they
    # can docker login + push. Admin-gated endpoint only.
    apps_registry_username: str = ""
    apps_registry_password: str = ""
    # External base domain/scheme used to derive each app's public URL
    # (<prefix>-<name>.<base>). Empty base => no public URL is advertised (LAN-only).
    external_base_domain: str = ""
    external_scheme: str = "https"
    # KELT's first-level namespace prefix. Public surfaces are <prefix>-<name>.<base>
    # (so edge apps and gnb are kelt-<name>.<base>), the catalogue is <prefix>.<base>.
    kelt_prefix: str = "kelt"
    backend_service_name: str = "dashboard-backend"
    frontend_service_name: str = "dashboard-frontend"
    # Optional external URL the dev frontend is reachable at. Used by the
    # prod UI to render an "Open dev" link. Empty leaves the link to
    # window.__ENV__.DASHBOARD_DEV_EXTERNAL_URL on the browser side.
    dev_external_url: str = ""

    audit_log_path: str = "logs/audit.log"
    # Days the dashboard keeps its own audit entries (audit_retention_days in
    # all.yml, set by the phase 09 unit; Keycloak keeps its events as long).
    audit_retention_days: int = 30
    cors_origin: str = "http://localhost:5173"

    # Subscriber snapshot Secret, named by all.yml subscriber_snapshot_secret (see
    # docs/architecture/subscriber-persistence.md)
    # Kept in sync with MongoDB on every subscriber change so the MongoDB pod can
    # re-seed itself from the latest state on restart.
    subscriber_snapshot_key: str = "snapshot.json"

    # ── Keycloak / OIDC ────────────────────────────────────────────────
    # Set skip_auth=True until phase 08 (IAM) is deployed and the realm is
    # reachable. When True, requests bypass JWT validation and behave as
    # dashboard-admin. See docs/security/iam.md.
    skip_auth: bool = True
    # Set by phase 09 (DASHBOARD_KEYCLOAK_URL): the Keycloak NodePort on the worker.
    keycloak_url: str
    keycloak_realm: str = "5g-testbed"
    # Client IDs accepted in the JWT "azp" / "aud" claims. The browser
    # dashboard issues tokens for "dashboard"; the read-only service
    # account issues tokens for "dashboard-readonly".
    keycloak_accepted_clients: str = "dashboard,dashboard-readonly"
    # Optional path prefix when Keycloak is served under a reverse proxy
    # (for example "/auth"). Leave empty for root-path deploys.
    keycloak_path_prefix: str = ""
    # Keycloak master-realm admin username, used with KEYCLOAK_ADMIN_PASSWORD
    # (read from .testbed.secrets) by the client-secret rotation endpoint.
    # Mirrors keycloak_admin_user in phase 08.
    keycloak_admin_user: str = "admin"

    def ensure_audit_dir(self) -> None:
        Path(self.audit_log_path).parent.mkdir(parents=True, exist_ok=True)


settings = Settings()
