---
# UE deployment defaults
kubeconfig_path: "/home/vagrant/kubeconfig"
ueransim_image: "jacobbista/comnetsemu-ueransim:latest"

# UE deployment configuration
ue_name: "ue"
ue_replicas: 1
ue_node: "worker"
ue_privileged: true

# Paths inside container
ue_config_path: "/UERANSIM/config/ue.yaml"
ue_binary_path: "/UERANSIM/build/nr-ue"
